version: '3.1'

services:

  mongo:
    image: mongo:4.4.6
    restart: always
  watch_dowg:
    build: .
    restart: always



# Mongo express for debugging :))
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
